#!/usr/bin/env bash

ensure_downloaded () {
    if ! [ -d $1 ] && [ $1 != "Testing2" ] && [ $1 != "Testing" ]
    then
        ~/private/diderot-cli/diderot_student download_assignment 15210:F19 $1
        mkdir $1
        tar -xzf *.tgz -C $1 --strip-components=1
        rm *.tgz
    fi
}

~/private/diderot-cli/diderot_student list_assignments "15210:F19" | tr -s " " "\n" | while read -r line; do ensure_downloaded "$line"; done;
