#!/usr/bin/env bash

ensure_downloaded () {
    if ! [ -d $1 ] && [ $1 != "Testing2" ] && [ $1 != "Testing" ]
    then
        /afs/cs.cmu.edu/academic/class/15210-s19/diderot-cli/diderot_student download_assignment 15210:F19 $1
        mkdir $1
        if tar -xzf *.tgz -C $1 --strip-components=1 2> /dev/null; then
            :
        else
            tar -xf *.tgz -C $1
        fi
        rm *.tgz
    fi
}
/afs/cs.cmu.edu/academic/class/15210-s19/diderot-cli/diderot_student list_assignments "15210:F19" | tr -s " " "\n" | while read -r line; do ensure_downloaded "$line"; done;
find . -empty -type d -delete
